# Generated by Django 4.0 on 2021-12-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('location', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('employee_count', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            related_name='company', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('title', models.CharField(default='', max_length=40)),
                ('picture', models.ImageField(upload_to='specialties')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('skills', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                              to='vacancies.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                                to='vacancies.specialty')),
            ],
        ),
    ]
