# Generated by Django 4.0 on 2022-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=64),
        ),
    ]
