# Generated by Django 4.0 on 2021-12-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id_comp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='id_job',
            field=models.IntegerField(default=0),
        ),
    ]
